#!/usr/bin/env bash
# Render the documentation site into site/.
#
#   bash .github/scripts/build-docs-site.sh
#
# Lives here rather than in the shared scripts folder because the docs workflow
# runs from a checkout of this repository alone and cannot reach anything
# outside it. Runs locally too, for previewing before pushing.
#
# The API reference under /apidocs/ is generated by pdoc from the docstrings in
# src/. It is part of the site rather than an afterthought: unlike Go, which has
# pkg.go.dev building a reference from the source of every published version,
# Python has nowhere that does this for a package, so nothing else will host it.
# Generating it from the same commit as the prose is what stops the two drifting
# apart.
#
# The prose is README.md until there is a docs/ tree, and both when there is.
# Rendering the README rather than waiting for a docs/ directory means the site
# says something true today instead of being a navigation entry pointing at a
# page nobody has written.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO_ROOT"
OUT="site"

command -v pandoc >/dev/null || { echo "pandoc is required" >&2; exit 1; }
command -v pdoc >/dev/null || { echo "pdoc is required: pip install pdoc" >&2; exit 1; }

# The option was renamed: --highlight-style in older pandoc,
# --syntax-highlighting in newer, and each rejects or deprecates the other.
# Ubuntu's package and a current Homebrew install sit on opposite sides of that
# change, so the flag is chosen rather than assumed.
if pandoc --help 2>&1 | grep -q -- '--syntax-highlighting'; then
  HIGHLIGHT=(--syntax-highlighting=tango)
else
  HIGHLIGHT=(--highlight-style=tango)
fi

rm -rf "$OUT"
mkdir -p "$OUT"

if compgen -G "docs/assets/*" > /dev/null; then
  mkdir -p "$OUT/assets"
  cp docs/assets/* "$OUT/assets/"
fi

cat > "$OUT/style.css" <<'CSS'
:root {
  color-scheme: light dark;
  --fg:#1a1a1a; --bg:#fff; --muted:#5f5f5f; --line:#e4e4e4;
  --accent:#b4451f; --code-bg:#f7f7f5; --nav-bg:#fbfbfa;
}
@media (prefers-color-scheme: dark) {
  :root { --fg:#e8e8e8; --bg:#161616; --muted:#9c9c9c; --line:#2d2d2d;
          --accent:#ff8a5c; --code-bg:#1e1e1e; --nav-bg:#1b1b1b; }
}
* { box-sizing:border-box; }
body { margin:0; background:var(--bg); color:var(--fg);
       font:16px/1.7 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif; }
nav.top { background:var(--nav-bg); border-bottom:1px solid var(--line);
          padding:.85rem 1.25rem; display:flex; gap:1.15rem; flex-wrap:wrap; align-items:baseline;
          position:sticky; top:0; z-index:10; }
nav.top .brand { display:inline-flex; align-items:center; gap:.5rem; font-weight:700;
                 letter-spacing:-.01em; margin-right:.5rem; }
nav.top a { color:var(--fg); text-decoration:none; font-size:.9rem; opacity:.78; }
nav.top a:hover { opacity:1; color:var(--accent); }
nav.top a.api { color:var(--accent); opacity:1; font-weight:600; }
nav.top a.enterprise { color:var(--fg); opacity:.78; }
nav.top a.enterprise:first-of-type { margin-left:auto; }
@media (max-width: 900px) { nav.top a.enterprise:first-of-type { margin-left:0; } }
main { max-width:47rem; margin:0 auto; padding:2.5rem 1.25rem 5rem; }
h1 { font-size:2rem; letter-spacing:-.025em; margin:0 0 1.5rem; }
h2 { font-size:1.3rem; letter-spacing:-.015em; margin:2.75rem 0 .85rem;
     padding-top:.4rem; border-top:1px solid var(--line); }
h3 { font-size:1.05rem; margin:1.75rem 0 .6rem; }
p, li { color:var(--fg); }
a { color:var(--accent); }
pre { background:var(--code-bg); border:1px solid var(--line); border-radius:8px;
      padding:1rem 1.15rem; overflow-x:auto; font-size:.855rem; line-height:1.55; }
code { font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; font-size:.9em; }
p code, li code, td code { background:var(--code-bg); border:1px solid var(--line);
      border-radius:4px; padding:.08em .35em; color:var(--accent); }
pre code { background:none; border:none; padding:0; color:inherit; }
table { border-collapse:collapse; width:100%; font-size:.92rem; display:block; overflow-x:auto; }
th,td { text-align:left; padding:.55rem .8rem; border-bottom:1px solid var(--line); vertical-align:top; }
th { color:var(--muted); font-weight:600; }
blockquote { border-left:3px solid var(--line); margin:1.25rem 0; padding:.2rem 0 .2rem 1.15rem; color:var(--muted); }
footer { max-width:47rem; margin:0 auto; padding:1.5rem 1.25rem 4rem;
         border-top:1px solid var(--line); color:var(--muted); font-size:.85rem; }
CSS

NAV='<nav class="top">
  <span class="brand">AceMQ for Python</span>
  <a href="index.html">Overview</a>
  <a class="api" href="apidocs/acemq_amqp.html">API reference</a>
  <a href="licence.html">Licence</a>
  <a class="enterprise" href="https://acemq.org/">JVM libraries</a>
  <a class="enterprise" href="https://acemq.org/acemq-go-amqp/">Go library</a>
  <a class="enterprise" href="https://acemq.org/acemq-dotnet-amqp/">.NET library</a>
  <a class="enterprise" href="https://acemq.com">Enterprise support</a>
</nav>
<main>'

FOOT='</main>
<footer>
  <a href="https://github.com/AceMQ-Company/acemq-python-amqp">AceMQ for Python</a> &mdash;
  Apache-2.0, and provided without warranty &mdash; see the
  <a href="licence.html">licence</a>.
  <a href="https://acemq.com">Enterprise support</a>.
  The JVM libraries are at <a href="https://acemq.org/">acemq.org</a>.
  Pre-1.0 and in development.
  RabbitMQ and Python are trademarks of their respective owners. This project is
  not affiliated with either.
</footer>'

printf '%s' "$NAV" > "$OUT/.nav.html"
printf '%s' "$FOOT" > "$OUT/.foot.html"

render() {
  local source="$1" base="$2" pagetitle="$3"
  pandoc "$source" \
    --from=gfm --to=html5 --standalone \
    --metadata pagetitle="$pagetitle" \
    "${HIGHLIGHT[@]}" \
    --css=style.css \
    --include-before-body="$OUT/.nav.html" \
    --include-after-body="$OUT/.foot.html" \
    --output "$OUT/$base.html"
  # Links between pages are written as .md so they work when the same files are
  # read on GitHub; only the rendered copy is rewritten. The anchor is kept: a
  # link to another page's section is written .md#section and must survive.
  perl -pi -e 's{href="([^":#]*)\.md(#[^"]*)?"}{href="$1.html$2"}g' "$OUT/$base.html"
  # The README points at the LICENSE file, which is a plain-text file at the
  # repository root and not a page. On the site it is licence.html.
  perl -pi -e 's{href="LICENSE"}{href="licence.html"}g' "$OUT/$base.html"
  echo "  rendered $base.html"
}

render README.md index "AceMQ for Python"

# The licence as a page, so the link in the README and the one in the footer
# both resolve rather than 404ing on a site that says it is Apache-2.0.
{ echo '# Licence'; echo; echo '```'; cat LICENSE; echo '```'; } > "$OUT/.licence.md"
render "$OUT/.licence.md" licence "Licence — AceMQ for Python"
rm -f "$OUT/.licence.md"

# A docs/ tree when there is one. There is not yet, and the loop is here rather
# than waiting to be added because the alternative is a site that silently stops
# including the prose somebody writes.
if compgen -G "docs/*.md" > /dev/null; then
  for f in docs/*.md; do
    base="$(basename "${f%.md}")"
    [ "$base" = "index" ] && continue
    title="$(head -n1 "$f" | sed 's/^#\{1,6\} *//')"
    render "$f" "$base" "$title — AceMQ for Python"
  done
fi

rm -f "$OUT/.nav.html" "$OUT/.foot.html"

# The API reference, from the docstrings in src/. Generated from this commit, so
# it cannot describe a version of the library that is not the one beside it.
#
# aio-pika has to be importable: pdoc imports what it documents, and
# acemq_amqp.rabbitmq would otherwise be a page saying only that the module
# could not be loaded.
#
# Every module named rather than the package alone. pdoc respects __all__ when a
# package defines one, and this package's __all__ lists the API's names rather
# than its modules -- so asking for "acemq_amqp" produces a reference for the
# two modules that happen to appear in it and silently omits the other twelve.
MODULES=$(python3 - <<'PY'
import pkgutil
import acemq_amqp

names = ["acemq_amqp"]
for info in pkgutil.walk_packages(acemq_amqp.__path__, "acemq_amqp."):
    names.append(info.name)
print(" ".join(sorted(names)))
PY
)
echo "  documenting: $MODULES"
# shellcheck disable=SC2086 -- a deliberate word split: one argument per module.
pdoc --output-directory "$OUT/apidocs" \
  --docformat restructuredtext \
  --no-search \
  $MODULES
echo "  rendered apidocs/"

# Jekyll would otherwise skip anything underscore-prefixed.
touch "$OUT/.nojekyll"

echo "Site written to $REPO_ROOT/$OUT/index.html"
