# Copyright 2026 AceMQ.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""The retry schedule, the queue names and the topology, against every language.

``contract-fixtures.json`` is generated by the Java library and committed
byte-for-byte by all five. It exists because every library used to test its own
arithmetic against its own expectations, which is a test that passes for as long
as the library is self-consistent and says nothing at all about whether the
libraries agree. Java shipped ``exponential`` with a multiplier of 5.0 and 10%
jitter through ten releases while Go, .NET, Python and Ruby doubled with 20%:
``exponential(5, 1s, 1m)`` produced ``1s, 5s, 25s, 60s`` there and
``1s, 2s, 4s, 8s`` here, and nothing failed anywhere. Three more divergences —
the retry rung's dead-letter exchange, the source queue's dead-letter arguments,
and the queue type — turned up the same way on the same afternoon, all four
found by a person reading five codebases side by side rather than by a suite.

Reading a number out of the fixture and comparing it to the same number read out
of this library would prove only that both can be read, so the expectations here
are derived wherever there is a second way to reach them: the policies are built
from the fixture's own ``how`` string rather than from a table written beside it,
the doubling is checked as arithmetic rather than as a list, the broker-wait
table is recomputed from the stated rule, and the rung names are rendered by a
second implementation written from the naming convention.

Two places where this library does not match the file are asserted as
divergences rather than smoothed over. Both are documented on the tests that
carry them: the sub-second rung name, which the fixture itself records as
unresolved, and the default maximum message age, which it does not.
"""

from __future__ import annotations

import hashlib
import json
import random
import re
from collections.abc import Iterator
from datetime import timedelta
from itertools import pairwise
from pathlib import Path
from typing import Any

import pytest
from fake_transport import FakeTransport

from acemq_amqp import (
    Ack,
    Message,
    RetryPolicy,
    Topology,
    accept,
    exponential_retry,
    fixed_retry,
    naming,
    no_retry,
)
from acemq_amqp.connection import Connection
from acemq_amqp.retry import DEFAULT_BROKER_WAIT_THRESHOLD, ZERO
from acemq_amqp.topology import (
    DEAD_LETTER_EXCHANGE,
    QUEUE_TYPE_ARG,
    QUORUM_QUEUE_TYPE,
    RETRY_EXCHANGE,
    rung_args,
)
from acemq_amqp.transport import QueueSpec

FIXTURE_PATH = Path(__file__).parent / "fixtures" / "contract-fixtures.json"

#: The bytes every library carries. Pinned here as well as in
#: ``scripts/check-fixtures.sh`` so that a copy edited in this repository fails
#: this suite rather than waiting for somebody to run the workspace script: a
#: library that has quietly agreed with its own edited fixture is worse off than
#: one carrying no fixture at all, because it still passes.
FIXTURE_SHA256 = "7f2fc515bc15c88a8ebe37d2eeac3bde7c6ab420c4958fb13f1aa5a9f0809b9b"

FIXTURES: dict[str, Any] = json.loads(FIXTURE_PATH.read_text())

SCHEDULES: list[dict[str, Any]] = FIXTURES["retrySchedules"]
JITTER: dict[str, Any] = FIXTURES["jitter"]
THRESHOLD: dict[str, Any] = FIXTURES["brokerWaitThreshold"]
NAMING: dict[str, Any] = FIXTURES["naming"]
RUNG_ARGUMENTS: list[dict[str, Any]] = FIXTURES["rungArguments"]
TOPOLOGY: dict[str, Any] = FIXTURES["topology"]
QUEUE_TYPES: dict[str, Any] = FIXTURES["queueTypeDefaults"]

QUEUE: str = NAMING["queue"]

#: Java's ``RetryPolicy`` defaults ``maxMessageAge`` to ``Duration.ofDays(365)``
#: and compares against it unconditionally. Go, .NET, Ruby and Python all treat
#: zero as "no age limit" instead. The number is here so the rows that turn on it
#: can be recognised rather than listed; see
#: :func:`test_the_only_rows_python_disagrees_with_are_the_default_age_limit`.


# --------------------------------------------------------------------------- #
# Reading the fixture's own descriptions, so nothing is copied by hand
# --------------------------------------------------------------------------- #

_UNIT_SECONDS = {"ms": 0.001, "h": 3600.0, "m": 60.0, "s": 1.0}

_HOW = re.compile(
    r"(?P<kind>exponential|fixed|none)\((?P<args>[^)]*)\)"
    r"(?:\.giveUpAfter\((?P<age>[^)]+)\))?"
)


def _duration(text: str) -> timedelta:
    """``1s``, ``24h``, ``500ms`` as a duration.

    Longest suffix first, so ``ms`` is not read as ``m`` followed by rubbish.
    """
    for suffix, seconds in _UNIT_SECONDS.items():
        if text.endswith(suffix):
            return timedelta(seconds=float(text[: -len(suffix)]) * seconds)
    raise ValueError(f"the fixture describes a duration this test cannot read: {text!r}")


def _policy_from(how: str) -> RetryPolicy:
    """The policy the fixture says it is describing, built from that description.

    The alternative is a table of policies written beside the fixture, which is a
    second copy of the same list and free to drift from it — and the drift would
    show up as a suite that agrees with itself about the wrong policy.
    """
    match = _HOW.fullmatch(how)
    if match is None:
        raise ValueError(f"the fixture describes a policy this test cannot build: {how!r}")
    args = [part.strip() for part in match["args"].split(",") if part.strip()]

    policy: RetryPolicy
    if match["kind"] == "none":
        policy = no_retry()
    elif match["kind"] == "fixed":
        policy = fixed_retry(int(args[0]), _duration(args[1]))
    else:
        ceiling = _duration(args[2]) if len(args) > 2 else ZERO
        policy = exponential_retry(int(args[0]), _duration(args[1]), ceiling)

    if match["age"] is not None:
        policy = policy.give_up_after(_duration(match["age"]))
    return policy


def _millis(delay: timedelta) -> int:
    return round(delay.total_seconds() * 1000)


def _named(name: str) -> dict[str, Any]:
    """One entry of ``retrySchedules`` by name."""
    for schedule in SCHEDULES:
        if schedule["name"] == name:
            return schedule
    raise AssertionError(f"the fixture has no policy called {name!r}")


def _schedule_id(schedule: dict[str, Any]) -> str:
    return str(schedule["name"])


# --------------------------------------------------------------------------- #
# Second implementations, written from the rule rather than from the library
# --------------------------------------------------------------------------- #


def _waits_in_broker_by_the_rule(delay_millis: int, threshold_millis: int) -> bool:
    """``brokerWaitThreshold.rule``, transcribed.

    "A wait at or above the threshold is held on a rung queue; anything below it,
    and anything zero or negative, is held in the consumer. A threshold of zero
    sends nothing to the broker."
    """
    if threshold_millis <= 0:
        return False
    if delay_millis <= 0:
        return False
    return delay_millis >= threshold_millis


def _rendered_by_hand(delay: timedelta) -> str:
    """The delay suffix of a rung name, from the convention rather than the code.

    Whole hours read as hours, whole minutes as minutes, anything else as
    seconds, and a delay that does not reach a second has no seconds to show.
    """
    seconds = int(delay.total_seconds())
    if seconds <= 0:
        return "0s"
    if seconds % 3600 == 0:
        return f"{seconds // 3600}h"
    if seconds % 60 == 0:
        return f"{seconds // 60}m"
    return f"{seconds}s"


def _queue_shape(spec: QueueSpec) -> tuple[str, bool, dict[str, Any]]:
    """A declared queue as the fixture describes one: type, durability, arguments.

    ``x-queue-type`` moves out of the arguments and becomes the type, because a
    classic queue is declared by leaving the argument off entirely — the spelling
    every AceMQ library sends — and the fixture records that absence as
    ``"classic"`` rather than as a missing key.
    """
    args = dict(spec.args)
    kind = str(args.pop(QUEUE_TYPE_ARG, "classic"))
    return kind, spec.durable, args


# --------------------------------------------------------------------------- #
# The file itself
# --------------------------------------------------------------------------- #


def test_the_fixture_is_the_one_java_generated() -> None:
    assert FIXTURES["generatedBy"] == "acemq-java-amqp ContractFixtures"
    digest = hashlib.sha256(FIXTURE_PATH.read_bytes()).hexdigest()
    assert digest == FIXTURE_SHA256, (
        "this repository's copy of contract-fixtures.json has been edited. "
        "Four other repositories carry the same bytes; regenerate from the Java "
        "library and copy to all five, or the copies are no longer a contract"
    )


def test_the_exchanges_this_library_manages_are_the_ones_in_the_fixture() -> None:
    assert FIXTURES["deadLetterExchange"] == DEAD_LETTER_EXCHANGE
    assert FIXTURES["retryExchange"] == RETRY_EXCHANGE
    assert FIXTURES["defaultBrokerWaitThresholdMillis"] == _millis(
        DEFAULT_BROKER_WAIT_THRESHOLD
    )


def test_every_policy_in_the_fixture_is_one_this_library_can_build() -> None:
    # A policy added to the fixture that nothing here knows how to build would
    # otherwise be skipped in silence, which is the failure this file exists to
    # stop, one level up.
    assert len(SCHEDULES) == 5
    for schedule in SCHEDULES:
        assert isinstance(_policy_from(schedule["how"]), RetryPolicy)


# --------------------------------------------------------------------------- #
# retrySchedules
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize("schedule", SCHEDULES, ids=_schedule_id)
def test_the_unjittered_delays_are_the_ones_every_library_produces(
    schedule: dict[str, Any],
) -> None:
    policy = _policy_from(schedule["how"])
    assert [_millis(delay) for delay in policy.schedule()] == schedule["scheduleMillis"]
    assert policy.max_attempts == schedule["maxAttempts"]
    assert policy.jitter_factor == schedule["jitterFactor"]
    assert _millis(policy.broker_wait_threshold) == schedule["brokerWaitThresholdMillis"]


@pytest.mark.parametrize("schedule", SCHEDULES, ids=_schedule_id)
def test_a_schedule_has_one_delay_fewer_than_it_has_attempts(
    schedule: dict[str, Any],
) -> None:
    # Derived rather than read: the last attempt is not followed by a wait, so
    # ``max_attempts`` deliveries need ``max_attempts - 1`` delays. This is what
    # caught nothing and would have caught the multiplier bug had anyone looked.
    policy = _policy_from(schedule["how"])
    assert len(policy.schedule()) == policy.max_attempts - 1


@pytest.mark.parametrize("schedule", SCHEDULES, ids=_schedule_id)
def test_each_delay_is_its_predecessor_multiplied_until_the_ceiling(
    schedule: dict[str, Any],
) -> None:
    """The arithmetic, checked as arithmetic.

    This is the assertion Java did not have. ``exponential`` doubles and ``fixed``
    repeats, and the ceiling clamps whatever the multiplier would have produced —
    so each delay is ``min(previous * multiplier, ceiling)`` and no list of
    numbers has to be trusted to say so.
    """
    how = schedule["how"]
    match = _HOW.fullmatch(how)
    assert match is not None
    args = [part.strip() for part in match["args"].split(",") if part.strip()]

    if match["kind"] == "none":
        assert schedule["scheduleMillis"] == []
        return

    multiplier = 2 if match["kind"] == "exponential" else 1
    ceiling = _millis(_duration(args[2])) if len(args) > 2 else 0

    delays = schedule["scheduleMillis"]
    assert delays[0] == _millis(_duration(args[1]))
    for previous, delay in pairwise(delays):
        expected = previous * multiplier
        if ceiling and expected > ceiling:
            expected = ceiling
        assert delay == expected, f"{how}: {delay} does not follow {previous}"


@pytest.mark.parametrize("schedule", SCHEDULES, ids=_schedule_id)
def test_the_rungs_are_the_distinct_long_waits_in_the_order_they_are_reached(
    schedule: dict[str, Any],
) -> None:
    policy = _policy_from(schedule["how"])
    rungs = [_millis(delay) for delay in policy.broker_rungs()]
    assert rungs == schedule["brokerRungDelaysMillis"]

    # And the same list worked out from the schedule and the threshold, which is
    # the definition rather than a second reading of the answer. A fixed policy
    # that waits a minute three times needs one queue, not three.
    threshold = schedule["brokerWaitThresholdMillis"]
    expected: list[int] = []
    for delay in schedule["scheduleMillis"]:
        if _waits_in_broker_by_the_rule(delay, threshold) and delay not in expected:
            expected.append(delay)
    assert schedule["brokerRungDelaysMillis"] == expected


@pytest.mark.parametrize("schedule", SCHEDULES, ids=_schedule_id)
def test_the_attempt_and_age_limits_decide_the_same_way(schedule: dict[str, Any]) -> None:
    """Every ``{attempt, messageAgeMillis, retries}`` row the fixture records.

    No row is exempt. Six used to be: Java defaulted a policy to a 365-day age
    limit where the other four defaulted to none, so the fixture said a year-old
    message was abandoned and this library retried it. Java now agrees that zero
    means no limit, and the exemption went with the divergence.
    """
    policy = _policy_from(schedule["how"])
    for decision in schedule["decisions"]:
        age = timedelta(milliseconds=decision["messageAgeMillis"])
        retries = policy.next_wait(decision["attempt"], age) is not None
        assert retries == decision["retries"], (
            f"{schedule['name']}: attempt {decision['attempt']} at age "
            f"{decision['messageAgeMillis']}ms"
        )
        # next_delay is the same decision with the location thrown away, and a
        # library where the two could disagree would retry in one code path and
        # dead-letter in the other.
        assert (policy.next_delay(decision["attempt"], age) is not None) == retries


def test_no_policy_carries_an_age_limit_nobody_asked_for() -> None:
    """The agreement that replaced a divergence.

    Java used to build every policy with ``Duration.ofDays(365)`` and compare
    against it unconditionally, so a message exactly a year old was abandoned by
    a policy nobody asked to give up on age, while Go, .NET, Ruby and this
    library all read zero as no limit and kept retrying. Four to one, and the
    fixture recorded Java's answer. Java moved: zero is the default and only
    ``giveUpAfter`` sets a limit.

    So this asserts the agreement rather than bounding a disagreement, and it
    fails if it ever exercises nothing — a test that quietly stops running is
    how the divergence it replaced survived ten releases.
    """
    a_year = timedelta(days=365)
    checked = 0
    for schedule in SCHEDULES:
        if schedule["hasMaxMessageAge"]:
            continue  # asked for a limit; the boundary test owns those

        assert schedule["maxMessageAgeMillis"] == 0, (
            f"{schedule['name']} has no age limit but records "
            f"{schedule['maxMessageAgeMillis']}ms; zero is how the fixture says "
            "unlimited, and hasMaxMessageAge is how it says which zero it means"
        )

        policy = _policy_from(schedule["how"])
        assert policy.max_message_age == ZERO

        if schedule["maxAttempts"] < 2:
            continue  # no_retry stops on attempts before age can matter

        assert policy.next_wait(1, a_year) is not None, (
            f"{schedule['name']} gave up on a year-old message; with no age "
            "limit it should still retry"
        )
        checked += 1

    assert checked, "no unlimited policy was exercised, so this proved nothing"


def test_an_age_limit_that_was_asked_for_is_honoured_to_the_millisecond() -> None:
    """The half of the age rule the libraries do agree on.

    ``giveUpAfter`` is inclusive: a message that has just reached the limit is
    abandoned, one a millisecond short of it is not. That boundary is what the
    ``exponential-give-up-on-age`` rows are for, and every library implements it
    as ``age >= limit``.
    """
    schedule = _named("exponential-give-up-on-age")
    policy = _policy_from(schedule["how"])
    limit = schedule["maxMessageAgeMillis"]
    assert _millis(policy.max_message_age) == limit

    assert policy.next_wait(1, timedelta(milliseconds=limit - 1)) is not None
    assert policy.next_wait(1, timedelta(milliseconds=limit)) is None


# --------------------------------------------------------------------------- #
# jitter
# --------------------------------------------------------------------------- #


@pytest.fixture
def _repeatable_jitter() -> Iterator[None]:
    """A seeded random source, so a bound this test asserts cannot pass by luck."""
    state = random.getstate()
    random.seed(20260908)
    yield
    random.setstate(state)


def test_the_jitter_factor_is_the_one_the_fixture_names() -> None:
    policy = _policy_from(_named(JITTER["policy"])["how"])
    assert policy.jitter_factor == JITTER["factor"]

    # The multipliers are the factor either side of one rather than two more
    # numbers to trust, which is what "applies in both directions" means.
    assert JITTER["appliesInBothDirections"] is True
    assert JITTER["minMultiplier"] == pytest.approx(1 - JITTER["factor"])
    assert JITTER["maxMultiplier"] == pytest.approx(1 + JITTER["factor"])


@pytest.mark.usefixtures("_repeatable_jitter")
def test_a_wait_spent_here_is_moved_both_ways_and_stays_inside_the_bounds() -> None:
    """Sampled, not read back.

    The fixture states the bounds; this asks the library for two thousand waits
    and checks that they land inside them, that both directions are used, and
    that none falls below the floor.
    """
    assert JITTER["appliesToConsumerWaits"] is True
    schedule = _named(JITTER["policy"])
    policy = _policy_from(schedule["how"])
    base = schedule["scheduleMillis"][0]
    assert not policy.waits_in_broker(timedelta(milliseconds=base))

    low = base * JITTER["minMultiplier"]
    high = base * JITTER["maxMultiplier"]
    seen = []
    for _ in range(2000):
        wait = policy.next_wait(1)
        assert wait is not None
        assert wait.in_broker is False
        millis = wait.delay.total_seconds() * 1000
        assert low <= millis <= high, f"{millis}ms is outside [{low}, {high}]"
        assert millis >= JITTER["flooredAtMillis"]
        seen.append(millis)

    assert min(seen) < base, "jitter never moved a wait earlier"
    assert max(seen) > base, "jitter never moved a wait later"
    # A herd that failed together must not come back together, which is the whole
    # point: two thousand draws should not be two thousand of the same number.
    assert len(set(seen)) > 1000


@pytest.mark.usefixtures("_repeatable_jitter")
def test_a_wait_the_broker_holds_is_never_moved() -> None:
    """A jittered delay would name a rung queue that does not exist.

    ``exponential-capped`` reaches 40s on its third attempt, which is above the
    threshold, so the wait is spent on ``orders.new.retry.40s`` — a queue whose
    time-to-live was fixed when it was declared.
    """
    assert JITTER["appliesToBrokerWaits"] is False
    schedule = _named("exponential-capped")
    policy = _policy_from(schedule["how"])
    scheduled = schedule["scheduleMillis"][2]
    assert policy.waits_in_broker(timedelta(milliseconds=scheduled))
    assert policy.jitter_factor > 0

    for _ in range(500):
        wait = policy.next_wait(3)
        assert wait is not None
        assert wait.in_broker is True
        assert _millis(wait.delay) == scheduled


def test_a_policy_without_jitter_returns_the_scheduled_wait_exactly() -> None:
    schedule = _named("fixed")
    assert schedule["jitterFactor"] == 0
    policy = _policy_from(schedule["how"])
    for _ in range(200):
        wait = policy.next_wait(1)
        assert wait is not None
        assert _millis(wait.delay) == schedule["scheduleMillis"][0]


# --------------------------------------------------------------------------- #
# brokerWaitThreshold
# --------------------------------------------------------------------------- #


def test_the_threshold_table_is_the_whole_table() -> None:
    assert len(THRESHOLD["cases"]) == 30
    assert THRESHOLD["defaultMillis"] == _millis(DEFAULT_BROKER_WAIT_THRESHOLD)


@pytest.mark.parametrize(
    "case",
    THRESHOLD["cases"],
    ids=lambda case: f"{case['thresholdMillis']}-{case['delayMillis']}",
)
def test_where_a_wait_is_spent(case: dict[str, Any]) -> None:
    delay = timedelta(milliseconds=case["delayMillis"])
    policy = no_retry().wait_in_broker_from(timedelta(milliseconds=case["thresholdMillis"]))

    assert policy.waits_in_broker(delay) is case["waitsInBroker"]
    # The same row worked out from the sentence in the fixture rather than from
    # the library, so agreement means two implementations rather than one.
    assert (
        _waits_in_broker_by_the_rule(case["delayMillis"], case["thresholdMillis"])
        is case["waitsInBroker"]
    )


async def test_a_threshold_of_zero_declares_no_rung_at_all() -> None:
    """The way out for a service that may not declare queues on its broker.

    The table says a zero threshold sends nothing to the broker; this is what
    that means for a topology, which is where it is felt.
    """
    policy = _policy_from(_named("exponential-capped")["how"]).wait_in_broker_from(ZERO)
    assert policy.broker_rungs() == []

    transport = FakeTransport()
    await Topology().queue(QUEUE, retry=policy).apply(transport)
    assert list(transport.queues) == [QUEUE]
    assert RETRY_EXCHANGE not in transport.exchanges
    assert transport.bindings == []


# --------------------------------------------------------------------------- #
# naming
# --------------------------------------------------------------------------- #


def test_where_a_message_goes_when_it_cannot_be_handled() -> None:
    assert naming.dead_letter_queue(QUEUE) == NAMING["deadLetterQueue"]
    assert naming.parked_queue(QUEUE) == NAMING["parkedQueue"]
    assert naming.DEAD_LETTER_SUFFIX == ".dlq"
    assert naming.PARKED_SUFFIX == ".parked"


@pytest.mark.parametrize(
    "row", NAMING["retryQueues"], ids=lambda row: str(row["delayMillis"])
)
def test_a_rung_is_named_the_way_the_convention_says(row: dict[str, Any]) -> None:
    """Rendered twice: once by the library, once by :func:`_rendered_by_hand`."""
    delay = timedelta(milliseconds=row["delayMillis"])
    assert naming.retry_queue(QUEUE, delay) == f"{QUEUE}.retry.{_rendered_by_hand(delay)}"


@pytest.mark.parametrize(
    "row", NAMING["retryQueues"], ids=lambda row: str(row["delayMillis"])
)
def test_the_rung_name_matches_the_fixture_above_a_second(row: dict[str, Any]) -> None:
    rendered = naming.retry_queue(QUEUE, timedelta(milliseconds=row["delayMillis"]))
    if row["delayMillis"] >= 1000:
        assert rendered == row["queue"]
        return
    # The one disagreement the fixture records rather than settles. Java renders
    # a sub-second delay in milliseconds; Go, Python and Ruby round to whole
    # seconds and reach zero. Asserted as what this library does, so a change to
    # either side of it shows up here.
    assert rendered == f"{QUEUE}.retry.0s"
    assert rendered != row["queue"]


def test_the_sub_second_disagreement_is_recorded_and_out_of_reach() -> None:
    note = NAMING["subSecondDisagreement"]
    assert "orders.new.retry.500ms" in note
    assert "orders.new.retry.0s" in note

    # Unreachable at the default threshold, which is why it is recorded rather
    # than urgent: a wait that short is spent in the consumer and never names a
    # queue at all.
    assert not no_retry().waits_in_broker(timedelta(milliseconds=500))


# --------------------------------------------------------------------------- #
# rungArguments
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize(
    "row", RUNG_ARGUMENTS, ids=lambda row: str(row["delayMillis"])
)
def test_a_rung_is_declared_with_exactly_three_arguments(row: dict[str, Any]) -> None:
    """The count as much as the values.

    A fourth argument is not a nicety: the broker compares a queue's arguments
    exactly, so a rung this library declares with one more key than the Java
    library sends is answered ``PRECONDITION_FAILED`` for whichever service
    arrives second, and that service cannot consume at all.
    """
    arguments = rung_args(QUEUE, timedelta(milliseconds=row["delayMillis"]))
    assert len(arguments) == 3
    assert arguments == row["arguments"]
    assert QUEUE_TYPE_ARG not in arguments


def test_every_rung_dead_letters_home_through_the_managed_exchange() -> None:
    # Read as a rule rather than row by row: the time-to-live is the delay, the
    # target is the retry exchange, and the routing key is the queue the message
    # came from. Python used to dead-letter a rung through the default exchange,
    # which works and is not what the other four do.
    for row in RUNG_ARGUMENTS:
        assert row["arguments"]["x-message-ttl"] == row["delayMillis"]
        assert row["arguments"]["x-dead-letter-exchange"] == RETRY_EXCHANGE
        assert row["arguments"]["x-dead-letter-routing-key"] == QUEUE


# --------------------------------------------------------------------------- #
# topology
# --------------------------------------------------------------------------- #

TOPOLOGY_POLICY = _policy_from(str(TOPOLOGY["policy"]).split(" at ")[0])


async def _declared(
    *, retry: RetryPolicy | None, transport: FakeTransport | None = None
) -> FakeTransport:
    """The fixture's topology, applied to a transport that records rather than connects."""
    transport = FakeTransport() if transport is None else transport
    await (
        Topology()
        .exchange("orders", "topic")
        .queue(TOPOLOGY["sourceQueue"], dead_letter=True, retry=retry)
        .binding(TOPOLOGY["sourceQueue"], "orders", "order.*")
    ).apply(transport)
    return transport


def _expect(entries: list[dict[str, Any]], *by: str) -> list[dict[str, Any]]:
    return [entry for entry in entries if entry["declaredBy"] in by]


def test_the_topology_policy_is_the_one_the_fixture_describes() -> None:
    assert TOPOLOGY_POLICY.broker_wait_threshold == DEFAULT_BROKER_WAIT_THRESHOLD
    assert [_millis(d) for d in TOPOLOGY_POLICY.schedule()] == TOPOLOGY["policyScheduleMillis"]
    assert [
        _millis(d) for d in TOPOLOGY_POLICY.broker_rungs()
    ] == TOPOLOGY["policyRungDelaysMillis"]


async def test_the_whole_declared_plan_is_what_a_topology_produces() -> None:
    """Every exchange, queue and binding in the fixture, whoever declares it there.

    ``declaredBy`` records which side is *obliged* to declare an entry, not which
    side is allowed to. Java's consumer declares the retry half and the
    dead-letter half when it starts; this library's consumer declares the same
    two since ADR-032 (see
    :func:`test_the_consumer_declares_its_half_and_only_its_half`). What is left
    to a topology in both is the ``topology`` group — the source queue, which
    only its owner can declare correctly, and the exchange a producer publishes
    to.

    ``Topology.queue(dead_letter=True, retry=policy)`` declares all three groups
    in one call, which is what a service should apply at deployment: it is
    reviewable ahead of time, and it is the only place ``x-dead-letter-exchange``
    can be put on the source queue.
    """
    transport = await _declared(retry=TOPOLOGY_POLICY)

    assert {name: (spec.kind, spec.durable) for name, spec in transport.exchanges.items()} == {
        entry["name"]: (entry["type"], entry["durable"])
        for entry in _expect(TOPOLOGY["exchanges"], "topology", "consumer", "both")
    }
    assert {name: _queue_shape(spec) for name, spec in transport.queues.items()} == {
        entry["name"]: (entry["type"], entry["durable"], entry["arguments"])
        for entry in _expect(TOPOLOGY["queues"], "topology", "consumer", "both")
    }
    assert set(transport.bindings) == {
        (entry["queue"], entry["exchange"], entry["routingKey"])
        for entry in _expect(TOPOLOGY["bindings"], "topology", "consumer", "both")
    }


async def test_without_a_policy_a_topology_declares_only_the_half_that_is_not_retry() -> None:
    """The ``topology`` and ``both`` groups, and nothing from ``consumer``.

    Neither half is the whole topology, which is why the fixture labels every
    entry: a service that declares its queue and its dead-letter queue but no
    rungs is a working service right up to the first long backoff, at which point
    the wait quietly moves back into the consumer.
    """
    transport = await _declared(retry=None)

    assert set(transport.exchanges) == {
        entry["name"] for entry in _expect(TOPOLOGY["exchanges"], "topology", "both")
    }
    assert {name: _queue_shape(spec) for name, spec in transport.queues.items()} == {
        entry["name"]: (entry["type"], entry["durable"], entry["arguments"])
        for entry in _expect(TOPOLOGY["queues"], "topology", "both")
    }
    assert set(transport.bindings) == {
        (entry["queue"], entry["exchange"], entry["routingKey"])
        for entry in _expect(TOPOLOGY["bindings"], "topology", "both")
    }

    for entry in _expect(TOPOLOGY["queues"], "consumer"):
        assert entry["name"] not in transport.queues


async def _consumed(transport: FakeTransport, **options: Any) -> None:
    """Starts and stops a consumer on the fixture's source queue."""

    async def handler(message: Message) -> Ack:
        return accept()

    connection = Connection(transport, retry=TOPOLOGY_POLICY)
    try:
        await connection.consume(TOPOLOGY["sourceQueue"], handler, **options)
    finally:
        await connection.close()


async def test_the_consumer_declares_its_half_and_only_its_half() -> None:
    """The ``consumer`` and ``both`` groups, declared by a consumer starting.

    This is ADR-032, and it is the assertion that used to say the opposite: this
    library's consumer declared nothing at all and left every queue to
    ``Topology``. The union was identical in a correctly deployed system, so
    nothing was ever missing — but in one where the topology had never been
    applied, a consumer that gave up republished to ``{queue}.dlq``, the broker
    could not route it, and the message was discarded without a trace. Declaring
    at start-up costs a few idempotent declares once per consumer and removes
    that path.

    Against a broker nothing has been applied to, so what is counted here is what
    the consumer itself declared. The source queue is not among it, deliberately:
    it belongs to whoever set the service up, and a guess at its type is a
    ``PRECONDITION_FAILED`` that stops the consumer starting at all.
    """
    transport = FakeTransport()
    await _consumed(transport)

    assert {name: (spec.kind, spec.durable) for name, spec in transport.exchanges.items()} == {
        entry["name"]: (entry["type"], entry["durable"])
        for entry in _expect(TOPOLOGY["exchanges"], "consumer", "both")
    }
    assert {name: _queue_shape(spec) for name, spec in transport.queues.items()} == {
        entry["name"]: (entry["type"], entry["durable"], entry["arguments"])
        for entry in _expect(TOPOLOGY["queues"], "consumer", "both")
    }
    assert set(transport.bindings) == {
        (entry["queue"], entry["exchange"], entry["routingKey"])
        for entry in _expect(TOPOLOGY["bindings"], "consumer", "both")
    }

    # Nothing from the ``topology`` group, which is the half a consumer must not
    # guess at: the source queue and the exchange a producer publishes to.
    for entry in _expect(TOPOLOGY["queues"], "topology"):
        assert entry["name"] not in transport.queues
    for entry in _expect(TOPOLOGY["exchanges"], "topology"):
        assert entry["name"] not in transport.exchanges


async def test_a_consumer_declares_the_same_arguments_a_topology_would() -> None:
    """Both ways round, because either order happens in a real deployment.

    A service that applies its topology and then starts a consumer, and one that
    starts a consumer against a broker somebody applied the topology to later,
    must both work. They do only if every argument matches to the key: a queue
    redeclared with anything different is refused with ``PRECONDITION_FAILED``,
    and the consumer cannot consume at all.
    """
    consumer_first = FakeTransport()
    await _consumed(consumer_first)
    after_topology = await _declared(retry=TOPOLOGY_POLICY, transport=consumer_first)

    topology_first = await _declared(retry=TOPOLOGY_POLICY)
    await _consumed(topology_first)

    assert {
        name: _queue_shape(spec) for name, spec in after_topology.queues.items()
    } == {name: _queue_shape(spec) for name, spec in topology_first.queues.items()}
    assert after_topology.exchanges == topology_first.exchanges
    assert set(after_topology.bindings) == set(topology_first.bindings)


async def test_a_consumer_told_not_to_declare_still_declares_nothing() -> None:
    """The escape hatch, and the only way back to the old behaviour.

    For a login with no ``configure`` permission on the vhost, and for a tool
    reading a queue it does not own. Everything it needs must then be declared by
    somebody else — which is what ``acemq.consumer.rung_missing`` and
    ``acemq.messages.set.aside.failed`` are there to report when it was not.
    """
    transport = await _declared(retry=TOPOLOGY_POLICY)

    def recorded() -> tuple[dict[str, Any], dict[str, Any], list[tuple[str, str, str]]]:
        return (
            dict(transport.queues),
            dict(transport.exchanges),
            list(transport.bindings),
        )

    before = recorded()
    await _consumed(transport, declare=False)
    assert recorded() == before


async def test_the_rungs_a_topology_declares_are_the_ones_the_policy_names() -> None:
    """The link the fixture's ``consumer`` group depends on.

    A rung the topology declares under a name the consumer will not publish to is
    a queue nobody uses and a retry that quietly waits in the consumer, so the
    delays and the names have to come from one value.
    """
    transport = await _declared(retry=TOPOLOGY_POLICY)
    for delay in TOPOLOGY_POLICY.broker_rungs():
        rung = naming.retry_queue(TOPOLOGY["sourceQueue"], delay)
        assert rung in transport.queues
        assert dict(transport.queues[rung].args) == rung_args(TOPOLOGY["sourceQueue"], delay)


# --------------------------------------------------------------------------- #
# queueTypeDefaults
# --------------------------------------------------------------------------- #


async def _one_queue(**kwargs: Any) -> FakeTransport:
    transport = FakeTransport()
    await Topology().queue(QUEUE, **kwargs).apply(transport)
    return transport


def _kind(transport: FakeTransport, name: str) -> str:
    return _queue_shape(transport.queues[name])[0]


async def test_a_durable_queue_is_a_quorum_queue() -> None:
    assert QUEUE_TYPES["sourceQueue"] == QUORUM_QUEUE_TYPE
    assert _kind(await _one_queue(), QUEUE) == QUEUE_TYPES["sourceQueue"]

    with_dlq = await _one_queue(dead_letter=True)
    assert _kind(with_dlq, QUEUE) == QUEUE_TYPES["sourceQueueWithDeadLetter"]


async def test_a_queue_asked_to_be_classic_is_declared_with_no_queue_type_at_all() -> None:
    # Classic is the absence of the argument, which is what the other four send
    # and therefore the only spelling a broker finds equivalent to theirs.
    plain = await _one_queue(quorum=False)
    assert QUEUE_TYPE_ARG not in plain.queues[QUEUE].args
    assert _kind(plain, QUEUE) == QUEUE_TYPES["explicitClassicQueue"]

    with_dlq = await _one_queue(quorum=False, dead_letter=True)
    assert _kind(with_dlq, QUEUE) == QUEUE_TYPES["explicitClassicQueueWithDeadLetter"]


async def test_the_queues_that_catch_what_a_queue_cannot_handle_stay_classic() -> None:
    transport = await _declared(retry=TOPOLOGY_POLICY)
    source = TOPOLOGY["sourceQueue"]

    assert _kind(transport, naming.dead_letter_queue(source)) == QUEUE_TYPES["deadLetterQueue"]
    assert _kind(transport, naming.parked_queue(source)) == QUEUE_TYPES["parkedQueue"]
    for delay in TOPOLOGY_POLICY.broker_rungs():
        assert _kind(transport, naming.retry_queue(source, delay)) == QUEUE_TYPES["retryRung"]


async def test_every_queue_a_topology_declares_is_durable() -> None:
    assert QUEUE_TYPES["durability"]["everyDeclaredQueueIsDurable"] is True
    transport = await _declared(retry=TOPOLOGY_POLICY)
    assert transport.queues
    for spec in transport.queues.values():
        assert spec.durable
        assert not spec.auto_delete
        assert not spec.exclusive


@pytest.mark.parametrize(
    "asked",
    [{"exclusive": True}, {"auto_delete": True}, {"durable": False}],
    ids=["exclusive", "auto-delete", "transient"],
)
async def test_a_queue_that_belongs_to_one_connection_stays_classic(
    asked: dict[str, Any],
) -> None:
    """The rule the fixture says Java cannot be asked about.

    ``queueTypeDefaults.durability`` records that the Java API offers no way to
    declare an exclusive, auto-delete or transient queue, so the rule that such a
    queue stays classic has nothing to attach to there and the ports that do
    offer the flags have to keep it. Python offers all three; this is that half of
    the contract being kept.
    """
    recorded = QUEUE_TYPES["durability"]["exclusiveAutoDeleteOrTransient"]
    assert "must keep them classic" in recorded

    transport = await _one_queue(**asked)
    assert QUEUE_TYPE_ARG not in transport.queues[QUEUE].args
    assert _kind(transport, QUEUE) == "classic"
