# Copyright 2026 AceMQ.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""The names AceMQ puts on the wire.

These are the contract between languages, not an implementation detail of this
one. A Python consumer reads what a Java producer wrote because both agree on
the strings in this module and on the types of their values, so nothing here is
renamed for Python's benefit — ``x-acemq-first-seen`` stays hyphenated and
stays epoch milliseconds, however un-Pythonic that looks.

The set is pinned by ``tests/fixtures/envelope-fixtures.json``, which is
generated by the Java implementation and shared with the Go and .NET ones.
"""

from __future__ import annotations

#: The unique message identifier, and the default idempotency key.
ID = "x-acemq-id"

#: The logical message type, for example ``order.placed.v2``.
TYPE = "x-acemq-type"

#: The schema version of the payload, as an integer starting at 1.
VERSION = "x-acemq-version"

#: The business correlation identifier, propagated across hops.
CORRELATION = "x-acemq-correlation"

#: The message that caused this one, absent when there was none.
CAUSATION = "x-acemq-causation"

#: The delivery attempt, as an integer starting at 1.
ATTEMPT = "x-acemq-attempt"

#: When the message was first published, as epoch milliseconds.
FIRST_SEEN = "x-acemq-first-seen"

#: The publishing process, conventionally ``service@host``.
ORIGIN = "x-acemq-origin"

#: Why a message was dead-lettered, present only when it was.
ERROR = "x-acemq-error"

#: The claim-check URI, when the payload is stored outside the message.
CLAIM = "x-acemq-claim"

#: The prefix every reserved name shares.
PREFIX = "x-acemq-"

#: Every name this library writes and understands.
RESERVED = frozenset(
    {ID, TYPE, VERSION, CORRELATION, CAUSATION, ATTEMPT, FIRST_SEEN, ORIGIN, ERROR, CLAIM}
)


def is_reserved(name: str) -> bool:
    """Whether a header name belongs to AceMQ rather than to the application.

    Matches on the prefix rather than on the known set: a header from a newer
    version of another language's library is still not the application's, and
    handing it back as though it were would have an application unknowingly
    copy it onto a message it publishes.

    :param name: a header name
    :returns: whether AceMQ reserves it
    """
    return name.startswith(PREFIX)
