# Copyright 2026 AceMQ.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Reads and writes Protocol Buffers::

    pip install "acemq-amqp[protobuf]"

    from acemq_amqp.codecs.protobuf import ProtobufCodec
    from myapp.orders_pb2 import OrderPlaced

    codec = ProtobufCodec(OrderPlaced)

**A codec is built for one message type**, the way it is in Java. Protobuf bytes
carry no name: they are field numbers and wire types, so a reader must already
know which message it is holding or the bytes are not interpretable at all. A
destination that has to carry several message types has to say which is which,
and the protobuf answer to that is a wrapper message with a ``oneof`` — a
decision about the schema rather than about the transport, so it belongs in the
``.proto`` file.

That is also why there is no factory registered under ``"protobuf"``: a codec
with no message type has nothing to read a message into.

Evolution is the format's own affair and works without anything here: readers
ignore fields they do not know and use defaults for fields that are absent,
provided nobody reuses a field number. Nothing in this codec can protect against
a reused number, and nothing can detect it either — the bytes are valid and mean
something else. Reserve retired numbers in the schema.

**This codec never volunteers for a message whose sender set no content type.**
Protobuf bytes are not recognisable and parse quietly into nonsense more often
than they fail, so guessing would produce a value that looks fine and is not.
"""

from __future__ import annotations

from typing import Any

from ..ack import FatalError
from ..errors import AceMQError

#: What this codec writes, and what Java, Go and .NET write.
PROTOBUF_CONTENT_TYPE = "application/x-protobuf"

#: Every content type this codec answers for, besides any ``+protobuf`` suffix.
#:
#: ``application/vnd.google.protobuf`` is the union of what the other libraries
#: accept rather than the intersection: Go accepts it and Java does not. It is
#: the type Google's own tooling writes, so a Java consumer refuses a message a
#: Go consumer beside it reads. Accepting it here costs nothing and closes the
#: hole in this direction; see the changelog entry.
PROTOBUF_ACCEPTS = (
    PROTOBUF_CONTENT_TYPE,
    "application/protobuf",
    "application/vnd.google.protobuf",
)


class ProtobufCodec:
    """Reads and writes one generated protobuf message type.

    :param message_type: a class generated by ``protoc``, as in
        ``orders_pb2.OrderPlaced``
    :raises AceMQError: when the protobuf runtime is not installed, or when the
        class given is not a generated message
    """

    def __init__(self, message_type: type[Any]) -> None:
        try:
            from google.protobuf.message import Message
        except ImportError as missing:  # pragma: no cover - depends on the install
            raise AceMQError(
                "acemq: ProtobufCodec needs the protobuf runtime, which is an optional "
                'extra. Install it with pip install "acemq-amqp[protobuf]"'
            ) from missing

        if not (isinstance(message_type, type) and issubclass(message_type, Message)):
            raise AceMQError(
                f"acemq: {message_type!r} does not look like a class protoc generated. "
                "ProtobufCodec takes the generated message class itself, as in "
                "ProtobufCodec(orders_pb2.OrderPlaced)."
            )

        self._message_type = message_type
        self._base = Message

    @property
    def content_type(self) -> str:
        return PROTOBUF_CONTENT_TYPE

    @property
    def message_type(self) -> type[Any]:
        """The one message type this codec reads and writes."""
        return self._message_type

    def encode(self, payload: Any) -> bytes:
        if not isinstance(payload, self._message_type):
            raise TypeError(
                f"acemq: this codec writes {self._message_type.__name__} and was given a "
                f"{type(payload).__name__}. Publish with JsonCodec to have an ordinary "
                "object encoded, or generate the message type from a .proto file."
            )
        serialized: bytes = payload.SerializeToString()
        return serialized

    def decode(self, body: bytes, content_type: str | None = None) -> Any:
        message = self._message_type()
        try:
            message.ParseFromString(body)
        except Exception as failure:
            # Fatal rather than retryable: bytes that are not this message will
            # not become it on a redelivery.
            raise FatalError(
                f"acemq: this message is not a {self._message_type.__name__}: {failure}"
            ) from failure
        return message

    def can_decode(self, content_type: str | None) -> bool:
        """Accepts the protobuf content types, and never an absent one."""
        if not content_type:
            return False
        lowered = content_type.lower()
        return lowered.startswith(PROTOBUF_ACCEPTS) or "+protobuf" in lowered

    def __repr__(self) -> str:
        return f"ProtobufCodec({self._message_type.__name__})"
